#!/bin/bash
cd root/alx-system_engineering-devops/0x02-shell_redirections#
echo "input file name"
read filename
echo "#!/bin/bash" > ${filename}
read -p "pleace enter the commit:"
message:"commit_message"
git add .
git commit -m ""
'$commit_message'
git push
